Import the libraries

In [16]:
# ---------- ALL IMPORTS (one place) ----------
import random
import re
import time
from datetime import datetime
from pathlib import Path
from urllib.parse import urlencode

import pandas as pd
from selenium import webdriver
from selenium.common.exceptions import NoSuchElementException, TimeoutException
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait

In [17]:
'''1. Settings'''
KEYWORD = "Data Scientist"
LOCATION = "India"
TARGET = 100

# find the project root (the folder that contains DATA)
ROOT = Path.cwd()
if not (ROOT / "DATA").exists():
    ROOT = ROOT.parent
OUT = ROOT / "DATA" / "jobs_cards.csv"
OUT.parent.mkdir(parents=True, exist_ok=True)

url = "https://www.linkedin.com/jobs/search?" + urlencode(
    {"keywords": KEYWORD, "location": LOCATION}
)
print("Project root:", ROOT)
print("Will save to:", OUT)

Project root: C:\Linkedin_Job_Analysis
Will save to: C:\Linkedin_Job_Analysis\DATA\jobs_cards.csv

## Scraping log
- Location for all searches: India
- Keywords scraped (one at a time, by changing KEYWORD in Cell 1 and running Cells 4 and 5):
  1. Data Analyst
  2. Data Scientist
  3. Data Engineer
  4. Business Analyst
  5. Power BI Developer
- Detail scraping (Cell 8) completed for all 332 jobs.
- Known issue: seniority/employment type/industries and some titles were missing; fixed by the repair cell (Cell 12).
- Re-run only the cells for a NEW keyword. Do not re-run Cells 4/5/8 for the old ones.

In [18]:
#2 functions (get_text, parse_card, load_more_cards)
def load_more_cards(driver, target):
    stuck = 0
    last_count = 0
    while True:
        count = len(driver.find_elements(By.CSS_SELECTOR, "div.base-card"))
        print("Loaded:", count)
        if count >= target:
            break
        if count == last_count:
            stuck += 1
            if stuck >= 4:
                print("No more jobs are loading. Stopping.")
                break
        else:
            stuck = 0
        last_count = count

        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(random.uniform(1.5, 2.5))
        try:
            button = driver.find_element(By.CSS_SELECTOR, "button.infinite-scroller__show-more-button")
            if button.is_displayed():
                driver.execute_script("arguments[0].click();", button)
                time.sleep(random.uniform(1.5, 2.5))
        except NoSuchElementException:
            pass
    return driver.find_elements(By.CSS_SELECTOR, "div.base-card")[:target]


def get_text(card, selector):
    try:
        return card.find_element(By.CSS_SELECTOR, selector).text.strip()
    except NoSuchElementException:
        return ""


def parse_card(card):
    """Turn one job card into a dictionary (one future CSV row)."""
    job = {
        "title": get_text(card, ".base-search-card__title"),
        "company": get_text(card, ".base-search-card__subtitle"),
        "location": get_text(card, ".job-search-card__location"),
        "posted_date": "",
        "posted_text": "",
        "job_url": "",
        "job_id": "",
    }
    try:
        t = card.find_element(By.CSS_SELECTOR, "time")
        job["posted_date"] = t.get_attribute("datetime") or ""
        job["posted_text"] = t.text.strip()
    except NoSuchElementException:
        pass
    try:
        href = card.find_element(By.CSS_SELECTOR, "a.base-card__full-link").get_attribute("href")
        job["job_url"] = href.split("?")[0]
    except NoSuchElementException:
        pass

    urn = card.get_attribute("data-entity-urn") or ""
    match = re.search(r"(\d{6,})", urn) or re.search(r"(\d{6,})$", job["job_url"])
    job["job_id"] = match.group(1) if match else ""
    return job

In [19]:
#3 Run scraper for cards
driver = webdriver.Chrome()
driver.set_window_size(1400, 1000)

try:
    driver.get(url)
    time.sleep(4)
    cards = load_more_cards(driver, TARGET)
    jobs = [parse_card(c) for c in cards]      # read the data BEFORE closing the browser
finally:
    driver.quit()

print("Jobs scraped:", len(jobs))

Loaded: 60
Loaded: 70
Loaded: 80
Loaded: 90
Loaded: 100
Jobs scraped: 100

In [20]:
#4 Save cards
new_cards = pd.DataFrame(jobs)
new_cards["search_keyword"] = KEYWORD
new_cards["search_location"] = LOCATION
new_cards = new_cards[new_cards["job_id"] != ""]          # drop cards without an id

print("New cards scraped:", len(new_cards))
print("\nEmpty values per column:")
print((new_cards == "").sum())

if OUT.exists():
    old = pd.read_csv(OUT, dtype={"job_id": str})
    combined = pd.concat([old, new_cards], ignore_index=True)
else:
    combined = new_cards

combined = combined.drop_duplicates(subset="job_id", keep="first")
combined.to_csv(OUT, index=False)
print("\nTotal unique cards in file:", len(combined))
combined.head()

New cards scraped: 100

Empty values per column:
title              0
company            0
location           0
posted_date        0
posted_text        0
job_url            0
job_id             0
search_keyword     0
search_location    0
dtype: int64

Total unique cards in file: 355

,title,company,location,posted_date,posted_text,job_url,job_id,search_keyword,search_location
0,Senior Data Analyst,EXL,"Bengaluru, Karnataka, India",2026-10-02,1 day ago,https://in.linkedin.com/jobs/view/senior-data-...,4446724293,Data Analyst,India
1,Senior Data Analyst,Finkraft,"Bangalore Urban, Karnataka, India",2026-06-27,3 months ago,https://in.linkedin.com/jobs/view/senior-data-...,4433474003,Data Analyst,India
2,Senior Data Analyst,Guidehouse,"Chennai, Tamil Nadu, India",2026-09-24,1 week ago,https://in.linkedin.com/jobs/view/senior-data-...,4471438516,Data Analyst,India
3,Senior Data Analyst I with Python Experience,ICE,"Pune Division, Maharashtra, India",2026-09-16,2 weeks ago,https://in.linkedin.com/jobs/view/senior-data-...,4459008614,Data Analyst,India
4,Assistant Manager,EXL,"Bengaluru, Karnataka, India",2026-10-02,1 day ago,https://in.linkedin.com/jobs/view/assistant-ma...,4446587231,Data Analyst,India

In [21]:
#5 "Detail functions"
RAW_OUT = ROOT / "DATA" / "jobs_raw.csv"

COLUMNS = ["job_id", "title", "company", "location", "posted_date", "posted_text",
           "job_url", "seniority_level", "employment_type", "job_function",
           "industries", "description", "search_keyword", "search_location", "scraped_at"]

CRITERIA_MAP = {"seniority level": "seniority_level", "employment type": "employment_type",
                "job function": "job_function", "industries": "industries"}

cards_df = pd.read_csv(OUT, dtype={"job_id": str}).fillna("")
print("Cards loaded:", len(cards_df))


def blocked(driver):
    u = driver.current_url.lower()
    return "authwall" in u or "/login" in u or "/checkpoint" in u


def read_job_details(driver, url):
    """Open one job page and return its details. Returns None if LinkedIn blocks us."""
    details = {"description": "", "seniority_level": "", "employment_type": "",
               "job_function": "", "industries": ""}
    driver.get(url)
    time.sleep(random.uniform(2, 4))
    if blocked(driver):
        return None
    try:
        WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "div.show-more-less-html__markup")))
    except TimeoutException:
        return details

    desc = driver.find_element(By.CSS_SELECTOR, "div.show-more-less-html__markup")
    raw_text = desc.get_attribute("textContent") or ""
    clean_text = re.sub(r"\s+", " ", raw_text)
    details["description"] = clean_text.strip()

    # wait for the criteria section too, instead of reading it immediately
    try:
        WebDriverWait(driver, 8).until(
            EC.presence_of_element_located((By.CSS_SELECTOR, "li.description__job-criteria-item")))
    except TimeoutException:
        pass

    for item in driver.find_elements(By.CSS_SELECTOR, "li.description__job-criteria-item"):
        header = get_text(item, "h3.description__job-criteria-subheader").lower()
        value = get_text(item, "span.description__job-criteria-text")
        if header in CRITERIA_MAP:
            details[CRITERIA_MAP[header]] = value
    return details


def parse_page_title(page_title):
    """'Data Analyst at EXL — Pune, India | LinkedIn Jobs' -> (title, company, location)"""
    t = page_title.replace(" | LinkedIn Jobs", "").replace(" | LinkedIn", "").strip()
    location = company = ""
    if " — " in t:
        t, location = t.rsplit(" — ", 1)
    if " at " in t:
        t, company = t.rsplit(" at ", 1)
    return t.strip(), company.strip(), location.strip()


def read_header(driver):
    """Title, company and location from the job page that is currently open."""
    page_title, company, location = parse_page_title(driver.title)
    title = ""
    for sel in ["h1.top-card-layout__title", "h2.top-card-layout__title"]:
        title = get_text(driver, sel)
        if title:
            break
    return {"title": title or page_title, "company": company, "location": location}

Cards loaded: 355

In [53]:
#6Test on 3 jobs
driver = webdriver.Chrome()
driver.set_window_size(1400, 1000)
try:
    for _, row in cards_df.head(3).iterrows():
        d = read_job_details(driver, row["job_url"])
        if d is None:
            print("Blocked by login wall"); break
        print(row["title"], "|", row["company"])
        print("   seniority:", d["seniority_level"], "| type:", d["employment_type"])
        print("   function:", d["job_function"], "| industries:", d["industries"])
        print("   description length:", len(d["description"]), "characters\n")
finally:
    driver.quit()

Senior Data Analyst | EXL
   seniority: Mid-Senior level | type: Full-time
   function:  | industries: Business Consulting and Services
   description length: 502 characters

Senior Data Analyst | Finkraft
   seniority: Mid-Senior level | type: Full-time
   function:  | industries: Financial Services
   description length: 2118 characters

Senior Data Analyst | Guidehouse
   seniority: Associate | type: Full-time
   function:  | industries: Business Consulting and Services
   description length: 4619 characters

In [42]:
#7 Scrape all job details
already_done = set()
if RAW_OUT.exists():
    already_done = set(pd.read_csv(RAW_OUT, dtype={"job_id": str})["job_id"])
print("Already saved:", len(already_done))

todo = cards_df[~cards_df["job_id"].isin(already_done)]
print("To scrape now:", len(todo))

driver = webdriver.Chrome()
driver.set_window_size(1400, 1000)
saved = 0
try:
    for _, row in todo.iterrows():
        details = read_job_details(driver, row["job_url"])
        if details is None:
            print("Login wall appeared. Stopping safely; your data so far is saved.")
            break
        job = row.to_dict()
        job.update(details)
        job["scraped_at"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        pd.DataFrame([job])[COLUMNS].to_csv(
            RAW_OUT, mode="a", index=False, header=not RAW_OUT.exists())
        saved += 1
        print(f"[{saved}/{len(todo)}] {job['title']} | {job['company']}")
finally:
    driver.quit()
    print("Done. Saved this run:", saved)

Already saved: 126
To scrape now: 206
[1/206]  |
[2/206]  |
[3/206]  |
[4/206]  |
[5/206]  |
[6/206]  |
[7/206]  |
[8/206]  |
[9/206]  |
[10/206]  |
[11/206]  |
[12/206]  |
[13/206]  |
[14/206]  |
[15/206]  |
[16/206]  |
[17/206]  |
[18/206]  |
[19/206]  |
[20/206]  |
[21/206]  |
[22/206]  |
[23/206]  |
[24/206]  |
[25/206]  |
[26/206]  |
[27/206]  |
[28/206]  |
[29/206]  |
[30/206]  |
[31/206]  |
[32/206]  |
[33/206]  |
[34/206]  |
[35/206]  |
[36/206]  |
[37/206]  |
[38/206]  |
[39/206]  |
[40/206]  |
[41/206]  |
[42/206]  |
[43/206]  |
[44/206]  |
[45/206]  |
[46/206]  |
[47/206]  |
[48/206]  |
[49/206]  |
[50/206]  |
[51/206]  |
[52/206]  |
[53/206]  |
[54/206]  |
[55/206]  |
[56/206]  |
[57/206] FBS Data Engineer | Capgemini
[58/206] Senior Data Engineer | Cloudwick
[59/206] Data Engineer | NK Securities Research
[60/206] Data Engineer Consultant II | Allstate India
[61/206] Sr. Business Analyst | VGreen Technology Solutions (VGreenTEK)
[62/206] Business Analyst | AU SMALL FINANCE BANK
[63/206] Assistant Manager - Business Analyst | BNP Paribas
[64/206] Business Analyst | Citi
[65/206] Senior Business Analyst - Health Insurance (Fully Remote) | CoverGo | Insurtech
[66/206] Business Analyst | Gowitek | Agentic AI + Digital Transformation Partner
[67/206] Senior Business Analyst | BNP Paribas
[68/206] Business Analyst | Automios
[69/206] Business Analyst - Health Insurance (Fully Remote) | CoverGo | Insurtech
[70/206] Business Analyst | IDFC FIRST Bank
[71/206] Sr. Business Analyst | Cognizant
[72/206] Salesforce Business Analyst | Tata Consultancy Services
[73/206] BUSINESS ANALYST | Aabasoft
[74/206] Salesforce Business Analyst | SPAR Solutions
[75/206] Business Analyst | SHRI KRISHNA PLACEMENT
[76/206] Business Analyst | Macquarie Group
[77/206] Volody - Senior Business Analyst - International Market Domain | Volody
[78/206] Business Analyst -Remote – Telecom | AireSpring
[79/206] Business Analysis | VMC Soft Technologies, Inc
[80/206] Business Analyst_OTC derivatives | Luxoft
[81/206] Business Analyst | Axtria - Ingenious Insights
[82/206] Revalsys Technologies - Business Analyst - Agile | Revalsys Technologies
[83/206] Senior Business Analyst | Citrus Informatics (India) Pvt Ltd
[84/206] Business Analyst - System Ticketing Platform | Ventra Health
[85/206] TD-BA Senior -US | EY
[86/206] Business Analyst | Flex
[87/206] BA Avaloq | Capco
[88/206] BA - Capital Market | Capco
[89/206] Murex Business Analyst (BA) | Unison Group
[90/206] Sr Business Analyst – ServiceNow | iBeris Software Solutions
[91/206] Associate - Business Analyst-Business Process & Service Excellence -Business Analyst | EXL
[92/206] Senior Business Analyst | Accenture in India
[93/206] Technical Business Analyst | Technoidentity
[94/206] Business Analyst - WFH | AlifCloud IT Consulting Pvt. Ltd.
[95/206] Domain Business Analyst | Tata Consultancy Services
[96/206] Senior Business Analyst | Elsevier
[97/206] Business Analyst | SourcingXPress
[98/206] Business Analyst | Tectoro Consulting Pvt. Ltd.
[99/206] Business Analyst/BSA/Process Analyst | Ascendion
[100/206] Senior Business Systems Analyst | ETS
[101/206] Product Definition Analyst 4 | Amadeus
[102/206] Business Analyst 2 | Simplify Alpha™
[103/206] BA - Partner Planet | L&T Finance
[104/206] ERP Business Analyst | Roche
[105/206] Senior Business Analyst - Pharmaceutical | Space Inventive
[106/206] Senior Business Analyst | Flattrade
[107/206] Sr Business Analyst | iCreative Technologies
[108/206] Consultant Business Analyst - Tax Transformation Office - Hyderabad / Gurugram | Deloitte
[109/206] Sr. Business Analyst II ( Policy Decision ) | Insurity
[110/206] Business Analyst | Poonawalla Fincorp
[111/206] Senior Consultant Business Analyst - Tax Transformation Office - Hyderabad / Gurugram | Deloitte
[112/206] Business Analyst - Trade Finance | IDFC FIRST Bank
[113/206] Senior Business Analyst, Technical Business Solutions | Cencora
[114/206] Business Analyst | Eicore
[115/206] Senior Business Analyst | CGI
[116/206] Senior Business Analyst | HTC Global Services
[117/206] Associate - Business Analyst | EXL
[118/206] Process Manager | eClerx
[119/206] Lead Business Analyst- Payment Domain- Pune- 6 to 10 Years | FIS
[120/206] Senior Business Analyst | IDFC FIRST Bank
[121/206] Business Analyst – SAP SD | VMC Soft Technologies, Inc
[122/206] Business Analyst | NEC Software Solutions (India)
[123/206] Business Analyst | Allianz Services
[124/206] Salesforce BA | InspireXT
[125/206] IND Senior Business Analyst | The Hartford India
[126/206] Senior Business Analyst | SS&C Technologies
[127/206] Senior Business Analyst – Payments | Persistent Systems
[128/206] Business Analyst | Arbaan – Migrations | Integrations | Automation
[129/206] Senior Business Analyst | SS&C Technologies
[130/206] FBS Business Analyst II- Guidewire | Capgemini
[131/206] Business Analyst | ECI
[132/206] BUSINESS ANALYST L3 | Wipro
[133/206] Business Analyst - SME / Commercial Lending | Luxoft
[134/206] Business Analyst - Interfaces, Officer | State Street
[135/206] Business Analyst - ServiceNow CSM | UST
[136/206] IT&D Senior Business Analyst - Genesis Procurement | Reckitt
[137/206] Senior Business Systems Analyst | Franklin Templeton
[138/206] Senior Business Analyst (Supply Chain Management) | Syren
[139/206] Distribution BA | SUN PHARMA
[140/206] Business Analyst (Cross-Portfolio) | Whitefield Careers
[141/206] Business Analyst | HireMap
[142/206] Senior Business Analyst | Sikich India
[143/206] Business Analyst – Life Sciences / G&A Data Platforms | Multiplier AI
[144/206] Business Analyst | MAN TRUCK & BUS INDIA PVT. LTD
[145/206] Senior Associate, Business Analyst - Global Capability Center | Alvarez & Marsal
[146/206] Business Analyst with Data Engineering | UST
[147/206] Sr. Power BI Developer | Programmers.ai
[148/206] Senior Power BI Developer | WillWare Technologies
[149/206] SAP Power BI Eng. & Developer | Tata Consultancy Services
[150/206] Senior BI Developer | ABC Fitness
[151/206] BI Specialist – Power BI & Data Visualization | DHL
[152/206] Senior Power BI Developer | EXL
[153/206] Senior PowerBI Developer - DOMO AI + SQL | UPS
[154/206] Power BI Developer with Property & Casualty Insurance | JMD Technologies Inc.
[155/206] Power BI Developer | Alight Solutions
[156/206] Technical Specialist - PBI Fabric | Datavail
[157/206] Senior PowerBI Developer - DOMO AI + SQL | UPS
[158/206] Power BI Developer / Data Analyst | KiddeFenwal
[159/206] Technology Consulting - Power BI Developer - Senior | EY
[160/206] Senior Power BI Developer | Verdantas
[161/206] PowerBI Developer | Withum
[162/206] Power bi +ADF | SWITS DIGITAL Private Limited
[163/206] GSPANN - Senior Power BI Developer - Data Analytics | GSPANN Technologies, Inc
[164/206] Power BI Developer | Office Beacon ASPL
[165/206] Power BI Developer | Whitefield Careers
[166/206] Senior Power BI Analysts | Ralph Lauren
[167/206] Business Intelligence Developer | WPP
[168/206] Sr. Power BI Developer | Programmers.io
[169/206] Analyst- Power BI & Microsoft Fabric | Evalueserve
[170/206] Senior Business Intelligence Analyst | Lonza
[171/206] Power BI Senior Engineer | SEI
[172/206] Ralph Lauren Senior Power BI Analysts | BoF Careers
[173/206] Technology Consulting - Power BI Developer - Senior | EY
[174/206] Lead Software Engineer - PowerBI/Data Expert | Societe Generale Global Solution Centre
[175/206] Senior BI Engineer - Power BI Subject Matter Expert | Blend
[176/206] Senior Power BI Developer | Metayb
[177/206] MSBI Developer | Exigo Tech
[178/206] Senior Business Intelligence Developer | CVM
[179/206] PowerBI Developer with Databricks (Virtual Interview) | Tata Consultancy Services
[180/206] Senior Data Analyst | Optum India
[181/206] Power BI Developer | Persistent Systems
[182/206] Sr. Software Engineer - Microsoft Power BI Job | YASH Technologies Middle East
[183/206] Senior Developer, Power BI | Hollister Incorporated
[184/206] Power BI Developer | Axis My India
[185/206] Data Consultant | WSP in India
[186/206] PowerBI Developer | Kumaran Systems
[187/206] Senior Power BI Migration Engineer (Tableau to Power BI) | Blend
[188/206] Power BI Developer | GlobalFoundries
[189/206] PowerBI on Fabric | Infosys
[190/206] Senior Power BI Developer - Advanced Analytics &amp; AI | Vista Info Systems
[191/206] Data Consultant | WSP in India
[192/206] Power BI Developer | NextGen Digital Solutions - NDS
[193/206] Power BI Developer - SoFi | EXL
[194/206] Power BI Developer | Exult Global
[195/206] Business Intelligence (BI) Engineer | Beckman Coulter Diagnostics
[196/206] Business Intelligence Developer | MHPI (Masco Home Products India)
[197/206] PowerBI developer | Withum
[198/206] Specialist Software Engineer - Senior Power BI Specialist | Societe Generale Global Solution Centre
[199/206] Senior Business Intelligence Developer | Supplier.io
[200/206] Technical Specialist-BI | Birlasoft
[201/206] Power BI Developer | Koundinyasa Technology Services
[202/206] Reflections Info Systems - Senior Power BI Developer - Artificial Intelligence | Vista Info Systems
[203/206] Power BI Developer | CloudSmartz | Netsmartz Group
[204/206] Senior Analytics Engineer - Power BI Development [T500-29608] | H.E. Services India
[205/206] Data Analyst | Sia
[206/206] Senior BI Analyst | Dentsu Global Services
Done. Saved this run: 206

In [22]:
#8 Check raw data
raw = pd.read_csv(RAW_OUT, dtype={"job_id": str})
print("Shape:", raw.shape)
print("\nEmpty values per column:")
print(raw.isna().sum())
print("\nDescription length (characters):")
print(raw["description"].fillna("").str.len().describe().round(0))
raw[["title", "company", "seniority_level", "employment_type", "description"]].head()

Shape: (332, 15)

Empty values per column:
job_id               0
title                0
company              0
location             0
posted_date          0
posted_text         56
job_url              0
seniority_level      0
employment_type      0
job_function       332
industries           0
description          0
search_keyword       0
search_location      0
scraped_at           0
dtype: int64

Description length (characters):
count      332.0
mean      3576.0
std       2098.0
min        373.0
25%       2029.0
50%       3496.0
75%       4661.0
max      15520.0
Name: description, dtype: float64

,title,company,seniority_level,employment_type,description
0,Senior Data Analyst,EXL,Mid-Senior level,Full-time,Title : Senior Data AnalystLocation : Bangalor...
1,Senior Data Analyst,Finkraft,Mid-Senior level,Full-time,About Finkraft.aiFinkraft.ai is a fast-growing...
2,Senior Data Analyst,Guidehouse,Associate,Full-time,Job FamilyEBO Management Information System (I...
3,Senior Data Analyst I with Python Experience,ICE,Not Applicable,Full-time,Job PurposeICE is the leading cloud-based plat...
4,Assistant Manager,EXL,Entry level,Full-time,Title - Data AnalystLocation - Bangalore (WFO)...

In [32]:
#9 "Check 1 / Check 2"
cards_now = pd.read_csv(OUT, dtype={"job_id": str})
saved_now = pd.read_csv(RAW_OUT, dtype={"job_id": str})
print("Cards in jobs_cards.csv:", len(cards_now))
print("Jobs in jobs_raw.csv:   ", len(saved_now))
print("Still to scrape:        ", (~cards_now["job_id"].isin(saved_now["job_id"])).sum())

# Check 2: what does LinkedIn really call the job function field?
driver = webdriver.Chrome()
try:
    driver.get(cards_now.loc[0, "job_url"])
    time.sleep(4)
    items = driver.find_elements(By.CSS_SELECTOR, "li.description__job-criteria-item")
    print("\nCriteria items found:", len(items))
    for item in items:
        print(repr(item.get_attribute("textContent").strip()))
finally:
    driver.quit()

Cards in jobs_cards.csv: 60
Jobs in jobs_raw.csv:    60
Still to scrape:         0

Criteria items found: 3
'Seniority level\n          \n          \n            Mid-Senior level'
'Employment type\n          \n          \n              Full-time'
'Industries\n            \n            \n            Business Consulting and Services'

In [44]:
#10. "diagnostic cell"
raw = pd.read_csv(RAW_OUT, dtype={"job_id": str})
raw["no_title"] = raw["title"].isna()
raw["no_criteria"] = raw["seniority_level"].isna()

print("Do the two problems overlap?")
print(pd.crosstab(raw["no_title"], raw["no_criteria"]), "\n")

print("Problems by search keyword:")
print(raw.groupby("search_keyword")[["no_title", "no_criteria"]].sum())
print(raw["search_keyword"].value_counts(), "\n")

# Open ONE job that is missing seniority and inspect the page
bad_url = raw.loc[raw["no_criteria"], "job_url"].iloc[0]
print("Inspecting:", bad_url)

driver = webdriver.Chrome()
driver.set_window_size(1400, 1000)
try:
    driver.get(bad_url)
    time.sleep(6)
    print("Page title:", driver.title)
    print("Criteria items found:", len(driver.find_elements(By.CSS_SELECTOR, "li.description__job-criteria-item")))
    print("'Seniority level' appears in page:", "Seniority level" in driver.page_source)
    print("Class names containing 'criteria':")
    print(driver.execute_script(
        "return [...new Set([...document.querySelectorAll('[class*=criteria]')].map(e => e.className))].slice(0, 10)"))
finally:
    driver.quit()

Do the two problems overlap?
no_criteria  False  True
no_title
False           60    216
True             0     56

Problems by search keyword:
                    no_title  no_criteria
search_keyword
Business Analyst           0           86
Data Analyst               0            0
Data Engineer             56           60
Data Scientist             0           66
Power BI Developer         0           60
search_keyword
Business Analyst      86
Data Scientist        66
Data Analyst          60
Data Engineer         60
Power BI Developer    60
Name: count, dtype: int64

Inspecting: https://in.linkedin.com/jobs/view/data-scientist-data-science-data-scientist-at-exl-4446725483
Page title: Data Scientist-Data Science-Data Scientist at EXL — Gurugram, Haryana, India | LinkedIn Jobs
Criteria items found: 3
'Seniority level' appears in page: True
Class names containing 'criteria':
['description__job-criteria-list', 'description__job-criteria-item', 'description__job-criteria-subheader', 'description__job-criteria-text description__job-criteria-text--criteria']

In [56]:
import shutil

LIMIT = 3            # 3 = dry run (nothing saved).  Set to None for the real repair.
SAVE = LIMIT is None

if SAVE:
    shutil.copy(RAW_OUT, ROOT / "DATA" / "jobs_raw_backup.csv")      # safety copy

raw = pd.read_csv(RAW_OUT, dtype={"job_id": str})
needs = (raw["title"].isna() | raw["company"].isna() | raw["location"].isna()
         | raw["seniority_level"].isna())
todo_idx = list(raw.index[needs])
print("Rows needing repair:", len(todo_idx))
if LIMIT:
    todo_idx = todo_idx[:LIMIT]

driver = webdriver.Chrome()
driver.set_window_size(1400, 1000)
try:
    for n, i in enumerate(todo_idx, start=1):
        details = read_job_details(driver, raw.at[i, "job_url"])
        if details is None:
            print("Login wall appeared. Stopping safely.")
            break

        # DEBUG: what did the scraper actually read from this page?
        print("   DEBUG details ->",
              "seniority:", repr(details["seniority_level"]),
              "| type:", repr(details["employment_type"]),
              "| industries:", repr(details["industries"]),
              "| description length:", len(details["description"]))

        info = read_header(driver)
        for col in ["seniority_level", "employment_type", "industries"]:
            info[col] = details[col]

        for col, val in info.items():
            if val and pd.isna(raw.at[i, col]):          # only fill blanks
                raw.at[i, col] = val

        print(f"[{n}/{len(todo_idx)}] {raw.at[i, 'title']} | {raw.at[i, 'company']} | "
              f"{raw.at[i, 'location']} | {raw.at[i, 'seniority_level']}")
        if SAVE and n % 10 == 0:
            raw.to_csv(RAW_OUT, index=False)             # save progress every 10 rows
finally:
    driver.quit()
    if SAVE:
        raw.to_csv(RAW_OUT, index=False)
        print("Saved to", RAW_OUT)

Rows needing repair: 272
   DEBUG details -> seniority: '' | type: '' | industries: '' | description length: 373
[1/3] Data Scientist-Data Science-Data Scientist | EXL | Gurugram, Haryana, India | nan
   DEBUG details -> seniority: '' | type: '' | industries: '' | description length: 1866
[2/3] Senior Data Scientist: 978 | C5i | Hyderabad, Telangana, India | nan
   DEBUG details -> seniority: '' | type: '' | industries: '' | description length: 1523
[3/3] Senior Data Scientist | LatentView Analytics | Chennai, Tamil Nadu, India | nan

In [9]:
import shutil
from pathlib import Path

ROOT = Path(r"C:\Linkedin_Job_Analysis")

RAW = ROOT / "DATA" / "jobs_raw.csv"
MAX_ROWS = None          # None = repair everything. Use 5 for a quick trial.
LABELS = {"seniority level": "seniority_level",
          "employment type": "employment_type",
          "industries": "industries"}


def txt(parent, selector):
    try:
        el = parent.find_element(By.CSS_SELECTOR, selector)
        return re.sub(r"\s+", " ", el.get_attribute("textContent") or "").strip()
    except NoSuchElementException:
        return ""


def header_from_page_title(page_title):
    """'C5i hiring Senior Data Scientist in Hyderabad, India | LinkedIn' -> title, company, location"""
    t = page_title.replace(" | LinkedIn", "").strip()
    company = title = location = ""
    if " hiring " in t:
        company, t = t.split(" hiring ", 1)
    if " in " in t:
        title, location = t.rsplit(" in ", 1)
    else:
        title = t
    return {"title": title.strip(), "company": company.strip(), "location": location.strip()}


def read_criteria(driver):
    for attempt in range(3):
        driver.execute_script("window.scrollTo(0, document.body.scrollHeight);")
        time.sleep(2)
        found = {}
        for item in driver.find_elements(By.CSS_SELECTOR, "li.description__job-criteria-item"):
            label = txt(item, "h3.description__job-criteria-subheader").lower()
            if label in LABELS:
                found[LABELS[label]] = txt(item, "span.description__job-criteria-text")
        if found:
            return found
        driver.execute_script("window.scrollTo(0, 0);")
        time.sleep(2)
    return {}


shutil.copy(RAW, ROOT / "DATA" / "jobs_raw_backup.csv")          # safety copy
raw = pd.read_csv(RAW, dtype={"job_id": str})
need_cols = ["title", "company", "location", "seniority_level", "employment_type", "industries"]
todo = list(raw.index[raw[need_cols].isna().any(axis=1)])
if MAX_ROWS:
    todo = todo[:MAX_ROWS]
print("Rows to repair:", len(todo))

driver = webdriver.Chrome()
driver.set_window_size(1400, 1000)
empty_streak = 0
try:
    for n, i in enumerate(todo, start=1):
        driver.get(raw.at[i, "job_url"])
        time.sleep(random.uniform(2, 3))
        u = driver.current_url.lower()
        if "authwall" in u or "/login" in u or "/checkpoint" in u:
            print("Login wall appeared. Stopping safely; progress is saved.")
            break

        info = header_from_page_title(driver.title)
        dom_title = txt(driver, "h1.top-card-layout__title") or txt(driver, "h2.top-card-layout__title")
        if dom_title:
            info["title"] = dom_title
        info.update(read_criteria(driver))

        got = 0
        for col, val in info.items():
            if val and pd.isna(raw.at[i, col]):
                raw.at[i, col] = val
                got += 1
        empty_streak = empty_streak + 1 if got == 0 else 0

        print(f"[{n}/{len(todo)}] filled {got} | {raw.at[i, 'title']} | {raw.at[i, 'company']} | {raw.at[i, 'seniority_level']}")
        if n % 10 == 0:
            raw.to_csv(RAW, index=False)
        if empty_streak >= 8:
            print("8 rows in a row gave nothing. Stopping so we do not waste time.")
            break
finally:
    driver.quit()
    raw.to_csv(RAW, index=False)
    print("\nSaved. Still missing per column:")
    print(raw[need_cols].isna().sum())

Rows to repair: 225
[1/225] filled 3 | Senior Data Scientist | Aditya Birla Capital | Mid-Senior level
[2/225] filled 3 | Senior Data Scientist | Capco | Mid-Senior level
[3/225] filled 3 | Data Scientist, Actimize | NiCE | Mid-Senior level
[4/225] filled 3 | Senior Data Scientist – Search | SproutsAI | Mid-Senior level
[5/225] filled 3 | Senior Data Scientist | IDFC FIRST Bank | Mid-Senior level
[6/225] filled 3 | Data Scientist Executive | GSTSahay | Mid-Senior level
[7/225] filled 3 | Data Scientist II | Bristol Myers Squibb | Entry level
[8/225] filled 3 | Data Scientist | Tata Consultancy Services | Not Applicable
[9/225] filled 3 | Senior Data Scientist | nference | Mid-Senior level
[10/225] filled 3 | Data Scientist | Thales | Not Applicable
[11/225] filled 3 | Data Scientist - Data Modeling/analytics | Amgen | Not Applicable
[12/225] filled 3 | Principal Data Scientist | Atlassian | Mid-Senior level
[13/225] filled 3 | Data Scientist - R01572015 | Brillio | Mid-Senior level
[14/225] filled 3 | Senior Data Scientist – Python, R, SQL, EDA, GCP, Vertex AI, IBM Watsonx | UPS | Mid-Senior level
[15/225] filled 3 | Senior Data Scientist | Thomson Reuters | Mid-Senior level
[16/225] filled 3 | Sr Data Scientist | F5 | Mid-Senior level
[17/225] filled 3 | Senior Data Scientist - Credit Risk | Funding Societies | Modalku Group | Mid-Senior level
[18/225] filled 3 | Data Scientist-Senior I | FedEx GCS | Entry level
[19/225] filled 3 | Data Scientist | Equifax | Mid-Senior level
[20/225] filled 4 | Data Engineer-I, SmartCommerce | nan | Not Applicable
[21/225] filled 4 | Data Engineer I, CMT | nan | Not Applicable
[22/225] filled 4 | Azure Data Engineer | nan | Mid-Senior level
[23/225] filled 4 | Senior Data Engineer | nan | Mid-Senior level
[24/225] filled 4 | AWS Data Engineer | nan | Mid-Senior level
[25/225] filled 4 | Lead II - Data Engineering | nan | Mid-Senior level
[26/225] filled 4 | Oliver Wyman - Data Engineer / Senior Data Engineer - Data and Analytics (DNA) - Gurugram, India | nan | Not Applicable
[27/225] filled 4 | Senior Databricks Data Engineer | nan | Mid-Senior level
[28/225] filled 4 | AWS Data Engineer | nan | Mid-Senior level
[29/225] filled 4 | Data Engineer / Senior Data Engineer (B) | nan | Entry level
[30/225] filled 4 | Senior Data Engineer | nan | Mid-Senior level
[31/225] filled 4 | Senior Data Engineer — Enterprise Data Platform | nan | Mid-Senior level
[32/225] filled 4 | Lead Data Engineer | nan | Mid-Senior level
[33/225] filled 4 | Data Engineer | nan | Mid-Senior level
[34/225] filled 4 | Azure Data Engineer | nan | Mid-Senior level
[35/225] filled 4 | Data Engineer-Data Platforms-Google | nan | Mid-Senior level
[36/225] filled 4 | Data Engineer-Data Platforms-Google | nan | Mid-Senior level
[37/225] filled 4 | Azure Databricks | nan | Mid-Senior level
[38/225] filled 4 | AI Data Engineer II | nan | Not Applicable
[39/225] filled 4 | Data Platforms Senior Engineer – Databricks | nan | Associate
[40/225] filled 4 | Data Engineer (Snowflake) | nan | Associate
[41/225] filled 4 | Senior Data Engineer | nan | Mid-Senior level
[42/225] filled 4 | Eucloid - Lead Data Engineer - ETL/Apache Spark | nan | Mid-Senior level
[43/225] filled 4 | Data Engineer | nan | Mid-Senior level
[44/225] filled 4 | LEAD DATA ENGINEER | nan | Mid-Senior level
[45/225] filled 4 | AWS Data Engineer_Bangalore / Hyderabad/Chennai/Pune/Mumbai_8 to 12 yrs | nan | Mid-Senior level
[46/225] filled 4 | Senior ETL Data Engineer | nan | Executive
[47/225] filled 4 | Senior Data Engineer | nan | Mid-Senior level
[48/225] filled 4 | Azure Data Engineering-Data Engineer III | nan | Not Applicable
[49/225] filled 4 | Data Engineer-Senior II-12 | nan | Entry level
[50/225] filled 4 | Big Data Developer (f/m/x) | nan | Mid-Senior level
[51/225] filled 4 | Data Engineer | nan | Associate
[52/225] filled 4 | QX Impact - Senior Data Engineer | nan | Mid-Senior level
[53/225] filled 4 | Sr. Data Engineer | nan | Mid-Senior level
[54/225] filled 4 | Data Engineer-Senior II-14 | nan | Entry level
[55/225] filled 4 | Azure Data Engineer | nan | Mid-Senior level
[56/225] filled 4 | Data Engineer II | nan | Not Applicable
[57/225] filled 4 | Principal Azure Data Engineer (12 to 15 yrs) (Python / PySpark / SQL/ DataBricks) - Remote India | nan | Mid-Senior level
[58/225] filled 4 | Data Engineer | nan | Mid-Senior level
[59/225] filled 4 | Senior Data Engineer | nan | Mid-Senior level
[60/225] filled 4 | Sr. Data Engineer – Clinical Data Foundation | nan | Not Applicable
[61/225] filled 4 | Data Ingestion Engineer (ADF+Dbt+Snowflake) | nan | Mid-Senior level
[62/225] filled 4 | Senior Data Engineer – Microsoft Fabric & Data Integration - Pune/Chennai | nan | Mid-Senior level
[63/225] filled 4 | Senior Data Engineer | nan | Mid-Senior level
[64/225] filled 4 | Data Engineer III | nan | Not Applicable
[65/225] filled 4 | Data Engineer - ETL | nan | Mid-Senior level
[66/225] filled 4 | Sr. Data Platform Engineer – Azure & Microsoft Fabric | nan | Mid-Senior level
[67/225] filled 4 | Data Engineer - Data Bricks | nan | Mid-Senior level
[68/225] filled 4 | AWS Data Engineer | nan | Associate
[69/225] filled 4 | Data Engineer | nan | Mid-Senior level
[70/225] filled 4 | Data Engineer - II (Biometrics) | nan | Mid-Senior level
[71/225] filled 4 | Senior Data Engineer | nan | Mid-Senior level
[72/225] filled 4 | Big Data Developer (f/m/x) | nan | Mid-Senior level
[73/225] filled 4 | Data Engineer II | nan | Mid-Senior level
[74/225] filled 4 | Associate Data Engineer | nan | Entry level
[75/225] filled 4 | Data Engineer III - Databricks | nan | Mid-Senior level
[76/225] filled 3 | FBS Data Engineer | Capgemini | Associate
[77/225] filled 3 | Senior Data Engineer | Cloudwick | Mid-Senior level
[78/225] filled 3 | Data Engineer | NK Securities Research | Entry level
[79/225] filled 3 | Data Engineer Consultant II | Allstate India | Mid-Senior level
[80/225] filled 3 | Sr. Business Analyst | VGreen Technology Solutions (VGreenTEK) | Mid-Senior level
[81/225] filled 3 | Business Analyst | AU SMALL FINANCE BANK | Mid-Senior level
[82/225] filled 3 | Assistant Manager - Business Analyst | BNP Paribas | Mid-Senior level
[83/225] filled 3 | Business Analyst | Citi | Not Applicable
[84/225] filled 3 | Senior Business Analyst - Health Insurance (Fully Remote) | CoverGo | Insurtech | Mid-Senior level
[85/225] filled 3 | Business Analyst | Gowitek | Agentic AI + Digital Transformation Partner | Associate
[86/225] filled 3 | Senior Business Analyst | BNP Paribas | Mid-Senior level
[87/225] filled 3 | Business Analyst | Automios | Mid-Senior level
[88/225] filled 3 | Business Analyst - Health Insurance (Fully Remote) | CoverGo | Insurtech | Mid-Senior level
[89/225] filled 3 | Business Analyst | IDFC FIRST Bank | Mid-Senior level
[90/225] filled 3 | Sr. Business Analyst | Cognizant | Mid-Senior level
[91/225] filled 3 | Salesforce Business Analyst | Tata Consultancy Services | Mid-Senior level
[92/225] filled 3 | BUSINESS ANALYST | Aabasoft | Entry level
[93/225] filled 3 | Salesforce Business Analyst | SPAR Solutions | Mid-Senior level
[94/225] filled 3 | Business Analyst | SHRI KRISHNA PLACEMENT | Mid-Senior level
[95/225] filled 3 | Business Analyst | Macquarie Group | Mid-Senior level
[96/225] filled 3 | Volody - Senior Business Analyst - International Market Domain | Volody | Mid-Senior level
[97/225] filled 3 | Business Analyst -Remote – Telecom | AireSpring | Mid-Senior level
[98/225] filled 3 | Business Analysis | VMC Soft Technologies, Inc | Mid-Senior level
[99/225] filled 3 | Business Analyst_OTC derivatives | Luxoft | Mid-Senior level
[100/225] filled 3 | Business Analyst | Axtria - Ingenious Insights | Mid-Senior level
[101/225] filled 3 | Revalsys Technologies - Business Analyst - Agile | Revalsys Technologies | Mid-Senior level
[102/225] filled 3 | Senior Business Analyst | Citrus Informatics (India) Pvt Ltd | Mid-Senior level
[103/225] filled 3 | Business Analyst - System Ticketing Platform | Ventra Health | Mid-Senior level
[104/225] filled 3 | TD-BA Senior -US | EY | Mid-Senior level
[105/225] filled 3 | Business Analyst | Flex | Entry level
[106/225] filled 3 | BA Avaloq | Capco | Mid-Senior level
[107/225] filled 3 | BA - Capital Market | Capco | Mid-Senior level
[108/225] filled 3 | Murex Business Analyst (BA) | Unison Group | Associate
[109/225] filled 3 | Sr Business Analyst – ServiceNow | iBeris Software Solutions | Mid-Senior level
[110/225] filled 3 | Associate - Business Analyst-Business Process & Service Excellence -Business Analyst | EXL | Entry level
[111/225] filled 3 | Senior Business Analyst | Accenture in India | Mid-Senior level
[112/225] filled 3 | Technical Business Analyst | Technoidentity | Mid-Senior level
[113/225] filled 3 | Business Analyst - WFH | AlifCloud IT Consulting Pvt. Ltd. | Mid-Senior level
[114/225] filled 3 | Domain Business Analyst | Tata Consultancy Services | Associate
[115/225] filled 3 | Senior Business Analyst | Elsevier | Mid-Senior level
[116/225] filled 3 | Business Analyst | SourcingXPress | Mid-Senior level
[117/225] filled 3 | Business Analyst | Tectoro Consulting Pvt. Ltd. | Mid-Senior level
[118/225] filled 3 | Business Analyst/BSA/Process Analyst | Ascendion | Not Applicable
[119/225] filled 3 | Senior Business Systems Analyst | ETS | Mid-Senior level
[120/225] filled 3 | Product Definition Analyst 4 | Amadeus | Mid-Senior level
[121/225] filled 3 | Business Analyst 2 | Simplify Alpha™ | Mid-Senior level
[122/225] filled 3 | BA - Partner Planet | L&T Finance | Mid-Senior level
[123/225] filled 3 | ERP Business Analyst | Roche | Associate
[124/225] filled 3 | Senior Business Analyst - Pharmaceutical | Space Inventive | Mid-Senior level
[125/225] filled 3 | Senior Business Analyst | Flattrade | Mid-Senior level
[126/225] filled 3 | Sr Business Analyst | iCreative Technologies | Mid-Senior level
[127/225] filled 3 | Consultant Business Analyst - Tax Transformation Office - Hyderabad / Gurugram | Deloitte | Not Applicable
[128/225] filled 3 | Sr. Business Analyst II ( Policy Decision ) | Insurity | Mid-Senior level
[129/225] filled 3 | Business Analyst | Poonawalla Fincorp | Mid-Senior level
[130/225] filled 3 | Senior Consultant Business Analyst - Tax Transformation Office - Hyderabad / Gurugram | Deloitte | Not Applicable
[131/225] filled 3 | Business Analyst - Trade Finance | IDFC FIRST Bank | Mid-Senior level
[132/225] filled 3 | Senior Business Analyst, Technical Business Solutions | Cencora | Mid-Senior level
[133/225] filled 3 | Business Analyst | Eicore | Mid-Senior level
[134/225] filled 3 | Senior Business Analyst | CGI | Entry level
[135/225] filled 3 | Senior Business Analyst | HTC Global Services | Associate
[136/225] filled 3 | Associate - Business Analyst | EXL | Entry level
[137/225] filled 3 | Process Manager | eClerx | Mid-Senior level
[138/225] filled 3 | Lead Business Analyst- Payment Domain- Pune- 6 to 10 Years | FIS | Mid-Senior level
[139/225] filled 3 | Senior Business Analyst | IDFC FIRST Bank | Mid-Senior level
[140/225] filled 3 | Business Analyst – SAP SD | VMC Soft Technologies, Inc | Associate
[141/225] filled 3 | Business Analyst | NEC Software Solutions (India) | Mid-Senior level
[142/225] filled 3 | Business Analyst | Allianz Services | Mid-Senior level
[143/225] filled 3 | Salesforce BA | InspireXT | Executive
[144/225] filled 3 | IND Senior Business Analyst | The Hartford India | Mid-Senior level
[145/225] filled 3 | Senior Business Analyst | SS&C Technologies | Mid-Senior level
[146/225] filled 3 | Senior Business Analyst – Payments | Persistent Systems | Mid-Senior level
[147/225] filled 3 | Business Analyst | Arbaan – Migrations | Integrations | Automation | Entry level
[148/225] filled 3 | Senior Business Analyst | SS&C Technologies | Mid-Senior level
[149/225] filled 3 | FBS Business Analyst II- Guidewire | Capgemini | Mid-Senior level
[150/225] filled 3 | Business Analyst | ECI | Mid-Senior level
[151/225] filled 3 | BUSINESS ANALYST L3 | Wipro | Not Applicable
[152/225] filled 3 | Business Analyst - SME / Commercial Lending | Luxoft | Mid-Senior level
[153/225] filled 3 | Business Analyst - Interfaces, Officer | State Street | Not Applicable
[154/225] filled 3 | Business Analyst - ServiceNow CSM | UST | Mid-Senior level
[155/225] filled 3 | IT&D Senior Business Analyst - Genesis Procurement | Reckitt | Mid-Senior level
[156/225] filled 3 | Senior Business Systems Analyst | Franklin Templeton | Mid-Senior level
[157/225] filled 3 | Senior Business Analyst (Supply Chain Management) | Syren | Mid-Senior level
[158/225] filled 3 | Distribution BA | SUN PHARMA | Mid-Senior level
[159/225] filled 3 | Business Analyst (Cross-Portfolio) | Whitefield Careers | Mid-Senior level
[160/225] filled 3 | Business Analyst | HireMap | Entry level
[161/225] filled 3 | Senior Business Analyst | Sikich India | Mid-Senior level
[162/225] filled 3 | Business Analyst – Life Sciences / G&A Data Platforms | Multiplier AI | Mid-Senior level
[163/225] filled 3 | Business Analyst | MAN TRUCK & BUS INDIA PVT. LTD | Mid-Senior level
[164/225] filled 3 | Senior Associate, Business Analyst - Global Capability Center | Alvarez & Marsal | Mid-Senior level
[165/225] filled 3 | Business Analyst with Data Engineering | UST | Mid-Senior level
[166/225] filled 3 | Sr. Power BI Developer | Programmers.ai | Mid-Senior level
[167/225] filled 3 | Senior Power BI Developer | WillWare Technologies | Mid-Senior level
[168/225] filled 3 | SAP Power BI Eng. & Developer | Tata Consultancy Services | Mid-Senior level
[169/225] filled 3 | Senior BI Developer | ABC Fitness | Mid-Senior level
[170/225] filled 3 | BI Specialist – Power BI & Data Visualization | DHL | Mid-Senior level
[171/225] filled 3 | Senior Power BI Developer | EXL | Mid-Senior level
[172/225] filled 3 | Senior PowerBI Developer - DOMO AI + SQL | UPS | Mid-Senior level
[173/225] filled 3 | Power BI Developer with Property & Casualty Insurance | JMD Technologies Inc. | Mid-Senior level
[174/225] filled 3 | Power BI Developer | Alight Solutions | Not Applicable
[175/225] filled 3 | Technical Specialist - PBI Fabric | Datavail | Mid-Senior level
[176/225] filled 3 | Senior PowerBI Developer - DOMO AI + SQL | UPS | Mid-Senior level
[177/225] filled 3 | Power BI Developer / Data Analyst | KiddeFenwal | Mid-Senior level
[178/225] filled 3 | Technology Consulting - Power BI Developer - Senior | EY | Mid-Senior level
[179/225] filled 3 | Senior Power BI Developer | Verdantas | Mid-Senior level
[180/225] filled 3 | PowerBI Developer | Withum | Associate
[181/225] filled 3 | Power bi +ADF | SWITS DIGITAL Private Limited | Mid-Senior level
[182/225] filled 3 | GSPANN - Senior Power BI Developer - Data Analytics | GSPANN Technologies, Inc | Mid-Senior level
[183/225] filled 3 | Power BI Developer | Office Beacon ASPL | Mid-Senior level
[184/225] filled 3 | Power BI Developer | Whitefield Careers | Associate
[185/225] filled 3 | Senior Power BI Analysts | Ralph Lauren | Associate
[186/225] filled 3 | Business Intelligence Developer | WPP | Mid-Senior level
[187/225] filled 3 | Sr. Power BI Developer | Programmers.io | Mid-Senior level
[188/225] filled 3 | Analyst- Power BI & Microsoft Fabric | Evalueserve | Entry level
[189/225] filled 3 | Senior Business Intelligence Analyst | Lonza | Not Applicable
[190/225] filled 3 | Power BI Senior Engineer | SEI | Mid-Senior level
[191/225] filled 3 | Ralph Lauren Senior Power BI Analysts | BoF Careers | Mid-Senior level
[192/225] filled 3 | Technology Consulting - Power BI Developer - Senior | EY | Mid-Senior level
[193/225] filled 3 | Lead Software Engineer - PowerBI/Data Expert | Societe Generale Global Solution Centre | Not Applicable
[194/225] filled 3 | Senior BI Engineer - Power BI Subject Matter Expert | Blend | Mid-Senior level
[195/225] filled 3 | Senior Power BI Developer | Metayb | Mid-Senior level
[196/225] filled 3 | MSBI Developer | Exigo Tech | Mid-Senior level
[197/225] filled 3 | Senior Business Intelligence Developer | CVM | Mid-Senior level
[198/225] filled 3 | PowerBI Developer with Databricks (Virtual Interview) | Tata Consultancy Services | Mid-Senior level
[199/225] filled 3 | Senior Data Analyst | Optum India | Mid-Senior level
[200/225] filled 3 | Power BI Developer | Persistent Systems | Mid-Senior level
[201/225] filled 3 | Sr. Software Engineer - Microsoft Power BI Job | YASH Technologies Middle East | Mid-Senior level
[202/225] filled 3 | Senior Developer, Power BI | Hollister Incorporated | Mid-Senior level
[203/225] filled 3 | Power BI Developer | Axis My India | Mid-Senior level
[204/225] filled 3 | Data Consultant | WSP in India | Mid-Senior level
[205/225] filled 3 | PowerBI Developer | Kumaran Systems | Mid-Senior level
[206/225] filled 3 | Senior Power BI Migration Engineer (Tableau to Power BI) | Blend | Mid-Senior level
[207/225] filled 3 | Power BI Developer | GlobalFoundries | Mid-Senior level
[208/225] filled 3 | PowerBI on Fabric | Infosys | Mid-Senior level
[209/225] filled 3 | Senior Power BI Developer - Advanced Analytics &amp; AI | Vista Info Systems | Mid-Senior level
[210/225] filled 3 | Data Consultant | WSP in India | Mid-Senior level
[211/225] filled 3 | Power BI Developer | NextGen Digital Solutions - NDS | Associate
[212/225] filled 3 | Power BI Developer - SoFi | EXL | Entry level
[213/225] filled 3 | Power BI Developer | Exult Global | Mid-Senior level
[214/225] filled 3 | Business Intelligence (BI) Engineer | Beckman Coulter Diagnostics | Not Applicable
[215/225] filled 3 | Business Intelligence Developer | MHPI (Masco Home Products India) | Entry level
[216/225] filled 3 | PowerBI developer | Withum | Associate
[217/225] filled 3 | Specialist Software Engineer - Senior Power BI Specialist | Societe Generale Global Solution Centre | Not Applicable
[218/225] filled 3 | Senior Business Intelligence Developer | Supplier.io | Mid-Senior level
[219/225] filled 3 | Technical Specialist-BI | Birlasoft | Mid-Senior level
[220/225] filled 3 | Power BI Developer | Koundinyasa Technology Services | Mid-Senior level
[221/225] filled 3 | Reflections Info Systems - Senior Power BI Developer - Artificial Intelligence | Vista Info Systems | Mid-Senior level
[222/225] filled 3 | Power BI Developer | CloudSmartz | Netsmartz Group | Mid-Senior level
[223/225] filled 3 | Senior Analytics Engineer - Power BI Development [T500-29608] | H.E. Services India | Mid-Senior level
[224/225] filled 3 | Data Analyst | Sia | Mid-Senior level
[225/225] filled 3 | Senior BI Analyst | Dentsu Global Services | Mid-Senior level

Saved. Still missing per column:
title               0
company            56
location           56
seniority_level     0
employment_type     0
industries          0
dtype: int64

In [11]:
RAW = ROOT / "DATA" / "jobs_raw.csv"
MAX_ROWS = None     # 3 = trial (nothing saved).  None = repair all 56 and save.


def txt(selector):
    try:
        el = driver.find_element(By.CSS_SELECTOR, selector)
        return re.sub(r"\s+", " ", el.get_attribute("textContent") or "").strip()
    except NoSuchElementException:
        return ""


raw = pd.read_csv(RAW, dtype={"job_id": str})
todo = list(raw.index[raw["company"].isna() | raw["location"].isna()])
print("Rows missing company/location:", len(todo))
if MAX_ROWS:
    todo = todo[:MAX_ROWS]
else:
    shutil.copy(RAW, ROOT / "DATA" / "jobs_raw_backup2.csv")

driver = webdriver.Chrome()
driver.set_window_size(1400, 1000)
try:
    for n, i in enumerate(todo, start=1):
        driver.get(raw.at[i, "job_url"])
        time.sleep(random.uniform(3, 4))
        u = driver.current_url.lower()
        if "authwall" in u or "/login" in u or "/checkpoint" in u:
            print("Login wall appeared. Stopping safely.")
            break

        company = txt("a.topcard__org-name-link") or txt(".topcard__flavor")
        location = txt("span.topcard__flavor--bullet")
        print(f"[{n}/{len(todo)}] page title: {driver.title}")
        print(f"      company: {company!r} | location: {location!r}")

        if company and pd.isna(raw.at[i, "company"]):
            raw.at[i, "company"] = company
        if location and pd.isna(raw.at[i, "location"]):
            raw.at[i, "location"] = location
        if MAX_ROWS is None and n % 10 == 0:
            raw.to_csv(RAW, index=False)
finally:
    driver.quit()
    if MAX_ROWS is None:
        raw.to_csv(RAW, index=False)
        print("\nSaved. Still missing:")
        print(raw[["company", "location"]].isna().sum())

Rows missing company/location: 56
[1/56] page title: Amazon hiring Data Engineer-I, SmartCommerce in Bengaluru, Karnataka, India | LinkedIn
      company: 'Amazon' | location: 'Bengaluru, Karnataka, India'
[2/56] page title: Amazon hiring Data Engineer I, CMT in Bengaluru, Karnataka, India | LinkedIn
      company: 'Amazon' | location: 'Bengaluru, Karnataka, India'
[3/56] page title: EXL hiring Azure Data Engineer in Pune Division, Maharashtra, India | LinkedIn
      company: 'EXL' | location: 'Pune Division, Maharashtra, India'
[4/56] page title: SourcingXPress hiring Senior Data Engineer in Ahmedabad, Gujarat, India | LinkedIn
      company: 'SourcingXPress' | location: 'Ahmedabad, Gujarat, India'
[5/56] page title: Infosys hiring AWS Data Engineer in Bengaluru East, Karnataka, India | LinkedIn
      company: 'Infosys' | location: 'Bengaluru East, Karnataka, India'
[6/56] page title: UST hiring Lead II - Data Engineering in Trivandrum, Kerala, India | LinkedIn
      company: 'UST' | location: 'Trivandrum, Kerala, India'
[7/56] page title: Oliver Wyman hiring Oliver Wyman - Data Engineer / Senior Data Engineer - Data and Analytics (DNA) - Gurugram, India in Gurugram, Haryana, India | LinkedIn
      company: 'Oliver Wyman' | location: 'Gurugram, Haryana, India'
[8/56] page title: Saarthee hiring Senior Databricks Data Engineer in Greater Kolkata Area | LinkedIn
      company: 'Saarthee' | location: 'Greater Kolkata Area'
[9/56] page title: EXL hiring AWS Data Engineer in Gurugram, Haryana, India | LinkedIn
      company: 'EXL' | location: 'Gurugram, Haryana, India'
[10/56] page title: v4c.ai hiring Data Engineer / Senior Data Engineer (B) in Pune Division, Maharashtra, India | LinkedIn
      company: 'v4c.ai' | location: 'Pune Division, Maharashtra, India'
[11/56] page title: SourcingXPress hiring Senior Data Engineer in Mumbai, Maharashtra, India | LinkedIn
      company: 'SourcingXPress' | location: 'Mumbai, Maharashtra, India'
[12/56] page title: Basware hiring Senior Data Engineer — Enterprise Data Platform in Chandigarh, India | LinkedIn
      company: 'Basware' | location: 'Chandigarh, India'
[13/56] page title: NationsBenefits hiring Lead Data Engineer in Hyderabad, Telangana, India | LinkedIn
      company: 'NationsBenefits' | location: 'Hyderabad, Telangana, India'
[14/56] page title: WPP hiring Data Engineer in Chennai, Tamil Nadu, India | LinkedIn
      company: 'WPP' | location: 'Chennai, Tamil Nadu, India'
[15/56] page title: Tata Consultancy Services hiring Azure Data Engineer in Thiruvananthapuram, Kerala, India | LinkedIn
      company: 'Tata Consultancy Services' | location: 'Thiruvananthapuram, Kerala, India'
[16/56] page title: IBM hiring Data Engineer-Data Platforms-Google in Chennai, Tamil Nadu, India | LinkedIn
      company: 'IBM' | location: 'Chennai, Tamil Nadu, India'
[17/56] page title: IBM hiring Data Engineer-Data Platforms-Google in Bengaluru, Karnataka, India | LinkedIn
      company: 'IBM' | location: 'Bengaluru, Karnataka, India'
[18/56] page title: Birlasoft hiring Azure Databricks in Pune/Pimpri-Chinchwad Area | LinkedIn
      company: 'Birlasoft' | location: 'Pune/Pimpri-Chinchwad Area'
[19/56] page title: UKG hiring AI Data Engineer II in Bengaluru East, Karnataka, India | LinkedIn
      company: 'UKG' | location: 'Bengaluru East, Karnataka, India'
[20/56] page title: Waters Corporation hiring Data Platforms Senior Engineer – Databricks in Bengaluru, Karnataka, India | LinkedIn
      company: 'Waters Corporation' | location: 'Bengaluru, Karnataka, India'
[21/56] page title: Shuru hiring Data Engineer (Snowflake) in Bengaluru, Karnataka, India | LinkedIn
      company: 'Shuru' | location: 'Bengaluru, Karnataka, India'
[22/56] page title: USEReady hiring Senior Data Engineer in Bengaluru, Karnataka, India | LinkedIn
      company: 'USEReady' | location: 'Bengaluru, Karnataka, India'
[23/56] page title: Eucloid Data Solutions hiring Eucloid - Lead Data Engineer - ETL/Apache Spark in Chennai, Tamil Nadu, India | LinkedIn
      company: 'Eucloid Data Solutions' | location: 'Chennai, Tamil Nadu, India'
[24/56] page title: AiVantage hiring Data Engineer in Ahmedabad, Gujarat, India | LinkedIn
      company: 'AiVantage' | location: 'Ahmedabad, Gujarat, India'
[25/56] page title: Eucloid Data Solutions hiring LEAD DATA ENGINEER in Chennai, Tamil Nadu, India | LinkedIn
      company: 'Eucloid Data Solutions' | location: 'Chennai, Tamil Nadu, India'
[26/56] page title: Tata Consultancy Services hiring AWS Data Engineer_Bangalore / Hyderabad/Chennai/Pune/Mumbai_8 to 12 yrs in Bengaluru, Karnataka, India | LinkedIn
      company: 'Tata Consultancy Services' | location: 'Bengaluru, Karnataka, India'
[27/56] page title: Kavi India hiring Senior ETL Data Engineer in Chennai, Tamil Nadu, India | LinkedIn
      company: 'Kavi India' | location: 'Chennai, Tamil Nadu, India'
[28/56] page title: Chevron hiring Senior Data Engineer in Bengaluru, Karnataka, India | LinkedIn
      company: 'Chevron' | location: 'Bengaluru, Karnataka, India'
[29/56] page title: Deloitte hiring Azure Data Engineering-Data Engineer III in Chennai, Tamil Nadu, India | LinkedIn
      company: 'Deloitte' | location: 'Chennai, Tamil Nadu, India'
[30/56] page title: FedEx hiring Data Engineer-Senior II-12 in Chennai, Tamil Nadu, India | LinkedIn
      company: 'FedEx' | location: 'Chennai, Tamil Nadu, India'
[31/56] page title: Sii Poland hiring Big Data Developer (f/m/x) in Bengaluru, Karnataka, India | LinkedIn
      company: 'Sii Poland' | location: 'Bengaluru, Karnataka, India'
[32/56] page title: Stealth AI Startup hiring Data Engineer in Greater Hyderabad Area | LinkedIn
      company: 'Stealth AI Startup' | location: 'Greater Hyderabad Area'
[33/56] page title: QX Impact hiring QX Impact - Senior Data Engineer in Greater Chennai Area | LinkedIn
      company: 'QX Impact' | location: 'Greater Chennai Area'
[34/56] page title: Numerator hiring Sr. Data Engineer in Vadodara, Gujarat, India | LinkedIn
      company: 'Numerator' | location: 'Vadodara, Gujarat, India'
[35/56] page title: FedEx hiring Data Engineer-Senior II-14 in Chennai, Tamil Nadu, India | LinkedIn
      company: 'FedEx' | location: 'Chennai, Tamil Nadu, India'
[36/56] page title: WillWare Technologies hiring Azure Data Engineer in Bengaluru, Karnataka, India | LinkedIn
      company: 'WillWare Technologies' | location: 'Bengaluru, Karnataka, India'
[37/56] page title: Thermo Fisher Scientific hiring Data Engineer II in Bengaluru East, Karnataka, India | LinkedIn
      company: 'Thermo Fisher Scientific' | location: 'Bengaluru East, Karnataka, India'
[38/56] page title: Nexaminds hiring Principal Azure Data Engineer (12 to 15 yrs) (Python / PySpark / SQL/ DataBricks) - Remote India in Coimbatore, Tamil Nadu, India | LinkedIn
      company: 'Nexaminds' | location: 'Coimbatore, Tamil Nadu, India'
[39/56] page title: StarRez, Inc. hiring Data Engineer in Hyderabad, Telangana, India | LinkedIn
      company: 'StarRez, Inc.' | location: 'Hyderabad, Telangana, India'
[40/56] page title: Entiovi Technologies hiring Senior Data Engineer in Kolkata, West Bengal, India | LinkedIn
      company: 'Entiovi Technologies' | location: 'Kolkata, West Bengal, India'
[41/56] page title: Amgen hiring Sr. Data Engineer – Clinical Data Foundation in Hyderabad, Telangana, India | LinkedIn
      company: 'Amgen' | location: 'Hyderabad, Telangana, India'
[42/56] page title: EVERSANA hiring Data Ingestion Engineer (ADF+Dbt+Snowflake) in Pune/Pimpri-Chinchwad Area | LinkedIn
      company: 'EVERSANA' | location: 'Pune/Pimpri-Chinchwad Area'
[43/56] page title: Wolters Kluwer hiring Senior Data Engineer – Microsoft Fabric & Data Integration - Pune/Chennai in Pune/Pimpri-Chinchwad Area | LinkedIn
      company: 'Wolters Kluwer' | location: 'Pune/Pimpri-Chinchwad Area'
[44/56] page title: Datavail hiring Senior Data Engineer in Mumbai, Maharashtra, India | LinkedIn
      company: 'Datavail' | location: 'Mumbai, Maharashtra, India'
[45/56] page title: Pearson hiring Data Engineer III in Chennai, Tamil Nadu, India | LinkedIn
      company: 'Pearson' | location: 'Chennai, Tamil Nadu, India'
[46/56] page title: Persistent Systems hiring Data Engineer - ETL in Pune City, Maharashtra, India | LinkedIn
      company: 'Persistent Systems' | location: 'Pune City, Maharashtra, India'
[47/56] page title: AVEVA hiring Sr. Data Platform Engineer – Azure & Microsoft Fabric in Mumbai Metropolitan Region | LinkedIn
      company: 'AVEVA' | location: 'Mumbai Metropolitan Region'
[48/56] page title: ValueMomentum hiring Data Engineer - Data Bricks in Hyderabad, Telangana, India | LinkedIn
      company: 'ValueMomentum' | location: 'Hyderabad, Telangana, India'
[49/56] page title: Infosys hiring AWS Data Engineer in Bhubaneswar, Odisha, India | LinkedIn
      company: 'Infosys' | location: 'Bhubaneswar, Odisha, India'
[50/56] page title: UST hiring Data Engineer in Kochi, Kerala, India | LinkedIn
      company: 'UST' | location: 'Kochi, Kerala, India'
[51/56] page title: Jumio Corporation hiring Data Engineer - II (Biometrics) in Bengaluru, Karnataka, India | LinkedIn
      company: 'Jumio Corporation' | location: 'Bengaluru, Karnataka, India'
[52/56] page title: Serko hiring Senior Data Engineer in Bengaluru, Karnataka, India | LinkedIn
      company: 'Serko' | location: 'Bengaluru, Karnataka, India'
[53/56] page title: Sii Poland hiring Big Data Developer (f/m/x) in Hyderabad, Telangana, India | LinkedIn
      company: 'Sii Poland' | location: 'Hyderabad, Telangana, India'
[54/56] page title: InXiteOut hiring Data Engineer II in Bengaluru, Karnataka, India | LinkedIn
      company: 'InXiteOut' | location: 'Bengaluru, Karnataka, India'
[55/56] page title: TaskUs hiring Associate Data Engineer in Mumbai Metropolitan Region | LinkedIn
      company: 'TaskUs' | location: 'Mumbai Metropolitan Region'
[56/56] page title: The Standard India hiring Data Engineer III - Databricks in Bengaluru East, Karnataka, India | LinkedIn
      company: 'The Standard India' | location: 'Bengaluru East, Karnataka, India'

Saved. Still missing:
company     0
location    0
dtype: int64